/**********************************************************
*Copyright(c) Automation Excellence Class
*FileName:  Map.h
*Author:  YJH
*Version:  //版本
*Date:  2017.8.29
*Description:  //用于主要说明此程序文件完成的主要功能
                //与其他模块或函数的接口、输出值、取值范围、
                //含义及参数间的控制、顺序、独立及依赖关系
*Others:  //其他内容说明
*Function List:  	
		1. void Draw_Arc(int centerx,int centery,int radius ,int color,int num);	
		   //！！！！！！！没什么通用性，暂时用！！！！！！
*History:  //修改历史记录列表，每条修改记录应包含修改日期、修改者及修改内容简介
    1.Date:
      Author:
      Modification:
    2.…………
**********************************************************/
#ifndef _Map_H_
#define _Map_H_

extern void Draw_Arc(int ,int ,int ,int ,int );
extern void Draw_DotLine(int, int, int, int, int);

#endif