/**********************************************************
*Copyright(c) Automation Excellence Class
*FileName: VGA.h
*Author: JH Yang
*Date:  2017/08/06
*Description: 设置自带的图形系统
*Others: NONE
*Function List:
	1.extern void Set_VGAMode(void);

*History:
	1.Date:
      Author:
      Modification:

**********************************************************/

#ifndef _VGA_H_
#define _VGA_H_

#include <dos.h>
#include <stdio.h>
#include <graphics.h>
#include <stdlib.h>
#include <conio.h>

extern void Set_VGAMode(void);

#endif